# Generated by Django 4.1.1 on 2022-09-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderitem_alter_cart_item_delete_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
